const theme = {
  colors: {
    primary: '#FF4759',
    primaryLight: '#FF7380',
    secondary: '#2C2E3F',
    secondaryLight: '#E6E8ED',
    backgroundDark: '#2C2E3F',
    backgroundLight: 'white',
    backgroundLightAlt: '#00BFBF',
    backgroundGrey: '#F8F8F8',
    error: '#FFAEB6',
    errorDark: '#CB2431',
    acepted: '#00D182',
    teal: '#00BBBB',
    tealLight: '#00BFBF',
    red: '#FF4759',
    grey: '#DDE1EA',
    greyDark: '#727D82',
    blueDark: '#00326E',
    greyLight: '#DBDBDB',
  },
  inputTheme: {
    borderColor: '#E5E5E5',
  },
  helpSectionTheme: {
    primary: '#00326E',
  },
  textTheme: {
    primaryColor: '#071A52',
    primaryColorLight: '#838CA8',
    secondaryColor: 'white',
    blueLight: '#59ade0',
    fontFamily: 'Poppins',
    placeholderPrimaryColor: '#838CA8',
    fontSize: {
      small: '0.8em',
      p: '0.9em',
      normal: '1em',
      h3: '1.25em',
      h2: '1.5em',
      h1: '2em',
    },
    bold: 'bold',
  },
  universalBorderRadius: '5px',
  contentMaxWidth: '980px',
  responsiveSizes: {
    xLarge: 1920,
    large: 1280,
    medium: 960,
    small: 600,
    xSmall: 480,
  },
};

export default theme;
